#!/bin/bash

matrixMultipicationCpp="matrixMultiplicationC++/matrixMultiplication_cpp"
matrixMultipicationRust="matrix_multiplication_rust/target/release/matrix_multiplication"
matrixMultipicationRustUnsafe="matrix_multiplication_rustUnsafe/target/release/matrix_multiplication"
mergeSortCpp="mergeSortC++/mergeSort_c++"
mergeSortRust="merge_sort_rust/target/release/merge_sort_rust"
readAndWriteCpp="readAndWriteC++/readWrite_cpp"
readAndWriteRust="read_write_rust/target/release/read_write_rust"

iterations="100"


# $matrixMultipicationCpp "250" "data/matrixMultData/firstMatrix250.txt" "data/matrixMultData/secondMatrix250.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "250"
# $matrixMultipicationCpp "375" "data/matrixMultData/firstMatrix375.txt" "data/matrixMultData/secondMatrix375.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "375"
# $matrixMultipicationCpp "500" "data/matrixMultData/firstMatrix500.txt" "data/matrixMultData/secondMatrix500.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "500"
# $matrixMultipicationCpp "750" "data/matrixMultData/firstMatrix750.txt" "data/matrixMultData/secondMatrix750.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "750"
# $matrixMultipicationCpp "1000" "data/matrixMultData/firstMatrix1000.txt" "data/matrixMultData/secondMatrix1000.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "1000"
# $matrixMultipicationCpp "1250" "data/matrixMultData/firstMatrix1250.txt" "data/matrixMultData/secondMatrix1250.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "1250"
# $matrixMultipicationCpp "1500" "data/matrixMultData/firstMatrix1500.txt" "data/matrixMultData/secondMatrix1500.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "1500"
# $matrixMultipicationCpp "1750" "data/matrixMultData/firstMatrix1750.txt" "data/matrixMultData/secondMatrix1750.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "1750"
# $matrixMultipicationCpp "2000" "data/matrixMultData/firstMatrix2000.txt" "data/matrixMultData/secondMatrix2000.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "2000"
# $matrixMultipicationCpp "2500" "data/matrixMultData/firstMatrix2500.txt" "data/matrixMultData/secondMatrix2500.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "2500"
# $matrixMultipicationCpp "3000" "data/matrixMultData/firstMatrix3000.txt" "data/matrixMultData/secondMatrix3000.txt" $iterations "resultFiles/c++Matrix/timeResult_"
# echo "3000"

# $matrixMultipicationRust "250" "data/matrixMultData/firstMatrix250.txt" "data/matrixMultData/secondMatrix250.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "250"
# $matrixMultipicationRust "375" "data/matrixMultData/firstMatrix375.txt" "data/matrixMultData/secondMatrix375.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "375"
# $matrixMultipicationRust "500" "data/matrixMultData/firstMatrix500.txt" "data/matrixMultData/secondMatrix500.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "500"
# $matrixMultipicationRust "750" "data/matrixMultData/firstMatrix750.txt" "data/matrixMultData/secondMatrix750.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "750"
# $matrixMultipicationRust "1000" "data/matrixMultData/firstMatrix1000.txt" "data/matrixMultData/secondMatrix1000.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "1000"
# $matrixMultipicationRust "1250" "data/matrixMultData/firstMatrix1250.txt" "data/matrixMultData/secondMatrix1250.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "1250"
# $matrixMultipicationRust "1500" "data/matrixMultData/firstMatrix1500.txt" "data/matrixMultData/secondMatrix1500.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "1500"
# $matrixMultipicationRust "1750" "data/matrixMultData/firstMatrix1750.txt" "data/matrixMultData/secondMatrix1750.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "1750"
# $matrixMultipicationRust "2000" "data/matrixMultData/firstMatrix2000.txt" "data/matrixMultData/secondMatrix2000.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "2000"
# $matrixMultipicationRust "2500" "data/matrixMultData/firstMatrix2500.txt" "data/matrixMultData/secondMatrix2500.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "2500"
# $matrixMultipicationRust "3000" "data/matrixMultData/firstMatrix3000.txt" "data/matrixMultData/secondMatrix3000.txt" $iterations "resultFiles/rustMatrix/timeResult_"
# echo "3000"


# $mergeSortCpp "100000" "data/sortData/sort10⁵.txt" $iterations "resultFiles/c++Sort/timeResult_"
# $mergeSortCpp "500000" "data/sortData/sort5*10⁵.txt" $iterations "resultFiles/c++Sort/timeResult_"
# $mergeSortCpp "1000000" "data/sortData/sort10⁶.txt" $iterations "resultFiles/c++Sort/timeResult_"
# $mergeSortCpp "5000000" "data/sortData/sort5*10⁶.txt" $iterations "resultFiles/c++Sort/timeResult_"
# $mergeSortCpp "10000000" "data/sortData/sort10⁷.txt" $iterations "resultFiles/c++Sort/timeResult_"
# $mergeSortCpp "50000000" "data/sortData/sort5*10⁷.txt" $iterations "resultFiles/c++Sort/timeResult_"
# $mergeSortCpp "100000000" "data/sortData/sort10⁸.txt" $iterations "resultFiles/c++Sort/timeResult_"
# $mergeSortCpp "200000000" "data/sortData/sort2*10⁸.txt" $iterations "resultFiles/c++Sort/timeResult_"

# $mergeSortRust "100000" "data/sortData/sort10⁵.txt" $iterations "resultFiles/rustSort/timeResult_"
# $mergeSortRust "500000" "data/sortData/sort5*10⁵.txt" $iterations "resultFiles/rustSort/timeResult_"
# $mergeSortRust "1000000" "data/sortData/sort10⁶.txt" $iterations "resultFiles/rustSort/timeResult_"
# $mergeSortRust "5000000" "data/sortData/sort5*10⁶.txt" $iterations "resultFiles/rustSort/timeResult_"
# $mergeSortRust "10000000" "data/sortData/sort10⁷.txt" $iterations "resultFiles/rustSort/timeResult_"
# $mergeSortRust "50000000" "data/sortData/sort5*10⁷.txt" $iterations "resultFiles/rustSort/timeResult_"
# $mergeSortRust "100000000" "data/sortData/sort10⁸.txt" $iterations "resultFiles/rustSort/timeResult_"
# $mergeSortRust "200000000" "data/sortData/sort2*10⁸.txt" $iterations "resultFiles/rustSort/timeResult_"

# $readAndWriteCpp "10000" "data/readWriteData/readWrite10⁴.txt" $iterations "resultFiles/c++ReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteCpp "100000" "data/readWriteData/readWrite10⁵.txt" $iterations "resultFiles/c++ReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteCpp "1000000" "data/readWriteData/readWrite10⁶.txt" $iterations "resultFiles/c++ReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteCpp "5000000" "data/readWriteData/readWrite5*10⁶.txt" $iterations "resultFiles/c++ReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteCpp "10000000" "data/readWriteData/readWrite10⁷.txt" $iterations "resultFiles/c++ReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteCpp "50000000" "data/readWriteData/readWrite5*10⁷.txt" $iterations "resultFiles/c++ReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteCpp "100000000" "data/readWriteData/readWrite10⁸.txt" $iterations "resultFiles/c++ReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteCpp "1000000000" "data/readWriteData/readWrite10⁹.txt" $iterations "resultFiles/c++ReadWrite/timeResult_"
# rm "result.txt"

# $readAndWriteRust "10000" "data/readWriteData/readWrite10⁴.txt" $iterations "resultFiles/rustReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteRust "100000" "data/readWriteData/readWrite10⁵.txt" $iterations "resultFiles/rustReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteRust "1000000" "data/readWriteData/readWrite10⁶.txt" $iterations "resultFiles/rustReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteRust "5000000" "data/readWriteData/readWrite5*10⁶.txt" $iterations "resultFiles/rustReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteRust "10000000" "data/readWriteData/readWrite10⁷.txt" $iterations "resultFiles/rustReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteRust "50000000" "data/readWriteData/readWrite5*10⁷.txt" $iterations "resultFiles/rustReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteRust "100000000" "data/readWriteData/readWrite10⁸.txt" $iterations "resultFiles/rustReadWrite/timeResult_"
# rm "result.txt"
# $readAndWriteRust "1000000000" "data/readWriteData/readWrite10⁹.txt" $iterations "resultFiles/rustReadWrite/timeResult_"
# rm "result.txt"



#2




# $matrixMultipicationCpp "250" "data/matrixMultData/firstMatrix250.txt" "data/matrixMultData/secondMatrix250.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "250"
# $matrixMultipicationCpp "375" "data/matrixMultData/firstMatrix375.txt" "data/matrixMultData/secondMatrix375.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "375"
# $matrixMultipicationCpp "500" "data/matrixMultData/firstMatrix500.txt" "data/matrixMultData/secondMatrix500.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "500"
# $matrixMultipicationCpp "750" "data/matrixMultData/firstMatrix750.txt" "data/matrixMultData/secondMatrix750.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "750"
# $matrixMultipicationCpp "1000" "data/matrixMultData/firstMatrix1000.txt" "data/matrixMultData/secondMatrix1000.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "1000"
# $matrixMultipicationCpp "1250" "data/matrixMultData/firstMatrix1250.txt" "data/matrixMultData/secondMatrix1250.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "1250"
# $matrixMultipicationCpp "1500" "data/matrixMultData/firstMatrix1500.txt" "data/matrixMultData/secondMatrix1500.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "1500"
# $matrixMultipicationCpp "1750" "data/matrixMultData/firstMatrix1750.txt" "data/matrixMultData/secondMatrix1750.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "1750"
# $matrixMultipicationCpp "2000" "data/matrixMultData/firstMatrix2000.txt" "data/matrixMultData/secondMatrix2000.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "2000"
# $matrixMultipicationCpp "2500" "data/matrixMultData/firstMatrix2500.txt" "data/matrixMultData/secondMatrix2500.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "2500"
# $matrixMultipicationCpp "3000" "data/matrixMultData/firstMatrix3000.txt" "data/matrixMultData/secondMatrix3000.txt" $iterations "resultFiles/c++Matrix/2timeResult"
# echo "3000"


# $matrixMultipicationRust "250" "data/matrixMultData/firstMatrix250.txt" "data/matrixMultData/secondMatrix250.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "250"
# $matrixMultipicationRust "375" "data/matrixMultData/firstMatrix375.txt" "data/matrixMultData/secondMatrix375.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "375"
# $matrixMultipicationRust "500" "data/matrixMultData/firstMatrix500.txt" "data/matrixMultData/secondMatrix500.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "500"
# $matrixMultipicationRust "750" "data/matrixMultData/firstMatrix750.txt" "data/matrixMultData/secondMatrix750.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "750"
# $matrixMultipicationRust "1000" "data/matrixMultData/firstMatrix1000.txt" "data/matrixMultData/secondMatrix1000.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "1000"
# $matrixMultipicationRust "1250" "data/matrixMultData/firstMatrix1250.txt" "data/matrixMultData/secondMatrix1250.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "1250"
# $matrixMultipicationRust "1500" "data/matrixMultData/firstMatrix1500.txt" "data/matrixMultData/secondMatrix1500.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "1500"
# $matrixMultipicationRust "1750" "data/matrixMultData/firstMatrix1750.txt" "data/matrixMultData/secondMatrix1750.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "1750"
# $matrixMultipicationRust "2000" "data/matrixMultData/firstMatrix2000.txt" "data/matrixMultData/secondMatrix2000.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "2000"
# $matrixMultipicationRust "2500" "data/matrixMultData/firstMatrix2500.txt" "data/matrixMultData/secondMatrix2500.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "2500"
# $matrixMultipicationRust "3000" "data/matrixMultData/firstMatrix3000.txt" "data/matrixMultData/secondMatrix3000.txt" $iterations "resultFiles/rustMatrix/2timeResult"
# echo "3000"

# $mergeSortCpp "100000" "data/sortData/sort10⁵.txt" $iterations "resultFiles/c++Sort/timeResult_2"
# $mergeSortCpp "500000" "data/sortData/sort5*10⁵.txt" $iterations "resultFiles/c++Sort/timeResult_2"
# $mergeSortCpp "1000000" "data/sortData/sort10⁶.txt" $iterations "resultFiles/c++Sort/timeResult_2"
# $mergeSortCpp "5000000" "data/sortData/sort5*10⁶.txt" $iterations "resultFiles/c++Sort/timeResult_2"
# $mergeSortCpp "10000000" "data/sortData/sort10⁷.txt" $iterations "resultFiles/c++Sort/timeResult_2"
# $mergeSortCpp "50000000" "data/sortData/sort5*10⁷.txt" $iterations "resultFiles/c++Sort/timeResult_2"
# $mergeSortCpp "100000000" "data/sortData/sort10⁸.txt" $iterations "resultFiles/c++Sort/timeResult_2"
# $mergeSortCpp "200000000" "data/sortData/sort2*10⁸.txt" $iterations "resultFiles/c++Sort/timeResult_2"

# $mergeSortRust "100000" "data/sortData/sort10⁵.txt" $iterations "resultFiles/rustSort/timeResult_2"
# $mergeSortRust "500000" "data/sortData/sort5*10⁵.txt" $iterations "resultFiles/rustSort/timeResult_2"
# $mergeSortRust "1000000" "data/sortData/sort10⁶.txt" $iterations "resultFiles/rustSort/timeResult_2"
# $mergeSortRust "5000000" "data/sortData/sort5*10⁶.txt" $iterations "resultFiles/rustSort/timeResult_2"
# $mergeSortRust "10000000" "data/sortData/sort10⁷.txt" $iterations "resultFiles/rustSort/timeResult_2"
# $mergeSortRust "50000000" "data/sortData/sort5*10⁷.txt" $iterations "resultFiles/rustSort/timeResult_2"
# $mergeSortRust "100000000" "data/sortData/sort10⁸.txt" $iterations "resultFiles/rustSort/timeResult_2"
# $mergeSortRust "200000000" "data/sortData/sort2*10⁸.txt" $iterations "resultFiles/rustSort/timeResult_2"

# $readAndWriteCpp "10000" "data/readWriteData/readWrite10⁴.txt" $iterations "resultFiles/c++ReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteCpp "100000" "data/readWriteData/readWrite10⁵.txt" $iterations "resultFiles/c++ReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteCpp "1000000" "data/readWriteData/readWrite10⁶.txt" $iterations "resultFiles/c++ReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteCpp "5000000" "data/readWriteData/readWrite5*10⁶.txt" $iterations "resultFiles/c++ReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteCpp "10000000" "data/readWriteData/readWrite10⁷.txt" $iterations "resultFiles/c++ReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteCpp "50000000" "data/readWriteData/readWrite5*10⁷.txt" $iterations "resultFiles/c++ReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteCpp "100000000" "data/readWriteData/readWrite10⁸.txt" $iterations "resultFiles/c++ReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteCpp "1000000000" "data/readWriteData/readWrite10⁹.txt" $iterations "resultFiles/c++ReadWrite/timeResult_2"
# rm "result.txt"

# $readAndWriteRust "10000" "data/readWriteData/readWrite10⁴.txt" $iterations "resultFiles/rustReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteRust "100000" "data/readWriteData/readWrite10⁵.txt" $iterations "resultFiles/rustReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteRust "1000000" "data/readWriteData/readWrite10⁶.txt" $iterations "resultFiles/rustReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteRust "5000000" "data/readWriteData/readWrite5*10⁶.txt" $iterations "resultFiles/rustReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteRust "10000000" "data/readWriteData/readWrite10⁷.txt" $iterations "resultFiles/rustReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteRust "50000000" "data/readWriteData/readWrite5*10⁷.txt" $iterations "resultFiles/rustReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteRust "100000000" "data/readWriteData/readWrite10⁸.txt" $iterations "resultFiles/rustReadWrite/timeResult_2"
# rm "result.txt"
# $readAndWriteRust "1000000000" "data/readWriteData/readWrite10⁹.txt" $iterations "resultFiles/rustReadWrite/timeResult_2"
# rm "result.txt"



#3




$matrixMultipicationCpp "250" "data/matrixMultData/firstMatrix250.txt" "data/matrixMultData/secondMatrix250.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "250"
$matrixMultipicationCpp "375" "data/matrixMultData/firstMatrix375.txt" "data/matrixMultData/secondMatrix375.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "375"
$matrixMultipicationCpp "500" "data/matrixMultData/firstMatrix500.txt" "data/matrixMultData/secondMatrix500.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "500"
$matrixMultipicationCpp "750" "data/matrixMultData/firstMatrix750.txt" "data/matrixMultData/secondMatrix750.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "750"
$matrixMultipicationCpp "1000" "data/matrixMultData/firstMatrix1000.txt" "data/matrixMultData/secondMatrix1000.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "1000"
$matrixMultipicationCpp "1250" "data/matrixMultData/firstMatrix1250.txt" "data/matrixMultData/secondMatrix1250.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "1250"
$matrixMultipicationCpp "1500" "data/matrixMultData/firstMatrix1500.txt" "data/matrixMultData/secondMatrix1500.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "1500"
$matrixMultipicationCpp "1750" "data/matrixMultData/firstMatrix1750.txt" "data/matrixMultData/secondMatrix1750.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "1750"
$matrixMultipicationCpp "2000" "data/matrixMultData/firstMatrix2000.txt" "data/matrixMultData/secondMatrix2000.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "2000"
$matrixMultipicationCpp "2500" "data/matrixMultData/firstMatrix2500.txt" "data/matrixMultData/secondMatrix2500.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "2500"
$matrixMultipicationCpp "3000" "data/matrixMultData/firstMatrix3000.txt" "data/matrixMultData/secondMatrix3000.txt" $iterations "resultFiles/c++Matrix/3timeResult"
echo "3000"

# $matrixMultipicationRust "250" "data/matrixMultData/firstMatrix250.txt" "data/matrixMultData/secondMatrix250.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "250"
# $matrixMultipicationRust "375" "data/matrixMultData/firstMatrix375.txt" "data/matrixMultData/secondMatrix375.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "375"
# $matrixMultipicationRust "500" "data/matrixMultData/firstMatrix500.txt" "data/matrixMultData/secondMatrix500.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "500"
# $matrixMultipicationRust "750" "data/matrixMultData/firstMatrix750.txt" "data/matrixMultData/secondMatrix750.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "750"
# $matrixMultipicationRust "1000" "data/matrixMultData/firstMatrix1000.txt" "data/matrixMultData/secondMatrix1000.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "1000"
# $matrixMultipicationRust "1250" "data/matrixMultData/firstMatrix1250.txt" "data/matrixMultData/secondMatrix1250.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "1250"
# $matrixMultipicationRust "1500" "data/matrixMultData/firstMatrix1500.txt" "data/matrixMultData/secondMatrix1500.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "1500"
# $matrixMultipicationRust "1750" "data/matrixMultData/firstMatrix1750.txt" "data/matrixMultData/secondMatrix1750.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "1750"
# $matrixMultipicationRust "2000" "data/matrixMultData/firstMatrix2000.txt" "data/matrixMultData/secondMatrix2000.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "2000"
# $matrixMultipicationRust "2500" "data/matrixMultData/firstMatrix2500.txt" "data/matrixMultData/secondMatrix2500.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "2500"
# $matrixMultipicationRust "3000" "data/matrixMultData/firstMatrix3000.txt" "data/matrixMultData/secondMatrix3000.txt" $iterations "resultFiles/rustMatrix/3timeResult"
# echo "3000"

# $mergeSortCpp "100000" "data/sortData/sort10⁵.txt" $iterations "resultFiles/c++Sort/timeResult_3"
# $mergeSortCpp "500000" "data/sortData/sort5*10⁵.txt" $iterations "resultFiles/c++Sort/timeResult_3"
# $mergeSortCpp "1000000" "data/sortData/sort10⁶.txt" $iterations "resultFiles/c++Sort/timeResult_3"
# $mergeSortCpp "5000000" "data/sortData/sort5*10⁶.txt" $iterations "resultFiles/c++Sort/timeResult_3"
# $mergeSortCpp "10000000" "data/sortData/sort10⁷.txt" $iterations "resultFiles/c++Sort/timeResult_3"
# $mergeSortCpp "50000000" "data/sortData/sort5*10⁷.txt" $iterations "resultFiles/c++Sort/timeResult_3"
# $mergeSortCpp "100000000" "data/sortData/sort10⁸.txt" $iterations "resultFiles/c++Sort/timeResult_3"
# $mergeSortCpp "200000000" "data/sortData/sort2*10⁸.txt" $iterations "resultFiles/c++Sort/timeResult_3"

# $mergeSortRust "100000" "data/sortData/sort10⁵.txt" $iterations "resultFiles/rustSort/timeResult_3"
# $mergeSortRust "500000" "data/sortData/sort5*10⁵.txt" $iterations "resultFiles/rustSort/timeResult_3"
# $mergeSortRust "1000000" "data/sortData/sort10⁶.txt" $iterations "resultFiles/rustSort/timeResult_3"
# $mergeSortRust "5000000" "data/sortData/sort5*10⁶.txt" $iterations "resultFiles/rustSort/timeResult_3"
# $mergeSortRust "10000000" "data/sortData/sort10⁷.txt" $iterations "resultFiles/rustSort/timeResult_3"
# $mergeSortRust "50000000" "data/sortData/sort5*10⁷.txt" $iterations "resultFiles/rustSort/timeResult_3"
# $mergeSortRust "100000000" "data/sortData/sort10⁸.txt" $iterations "resultFiles/rustSort/timeResult_3"
# $mergeSortRust "200000000" "data/sortData/sort2*10⁸.txt" $iterations "resultFiles/rustSort/timeResult_3"

# $readAndWriteCpp "10000" "data/readWriteData/readWrite10⁴.txt" $iterations "resultFiles/c++ReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteCpp "100000" "data/readWriteData/readWrite10⁵.txt" $iterations "resultFiles/c++ReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteCpp "1000000" "data/readWriteData/readWrite10⁶.txt" $iterations "resultFiles/c++ReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteCpp "5000000" "data/readWriteData/readWrite5*10⁶.txt" $iterations "resultFiles/c++ReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteCpp "10000000" "data/readWriteData/readWrite10⁷.txt" $iterations "resultFiles/c++ReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteCpp "50000000" "data/readWriteData/readWrite5*10⁷.txt" $iterations "resultFiles/c++ReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteCpp "100000000" "data/readWriteData/readWrite10⁸.txt" $iterations "resultFiles/c++ReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteCpp "1000000000" "data/readWriteData/readWrite10⁹.txt" $iterations "resultFiles/c++ReadWrite/timeResult_3"
# rm "result.txt"

# $readAndWriteRust "10000" "data/readWriteData/readWrite10⁴.txt" $iterations "resultFiles/rustReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteRust "100000" "data/readWriteData/readWrite10⁵.txt" $iterations "resultFiles/rustReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteRust "1000000" "data/readWriteData/readWrite10⁶.txt" $iterations "resultFiles/rustReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteRust "5000000" "data/readWriteData/readWrite5*10⁶.txt" $iterations "resultFiles/rustReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteRust "10000000" "data/readWriteData/readWrite10⁷.txt" $iterations "resultFiles/rustReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteRust "50000000" "data/readWriteData/readWrite5*10⁷.txt" $iterations "resultFiles/rustReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteRust "100000000" "data/readWriteData/readWrite10⁸.txt" $iterations "resultFiles/rustReadWrite/timeResult_3"
# rm "result.txt"
# $readAndWriteRust "1000000000" "data/readWriteData/readWrite10⁹.txt" $iterations "resultFiles/rustReadWrite/timeResult_3"
# rm "result.txt"